Introduce integration tests for the CFAPI operator
* Introduce a workflow action that runs the integration test on PRs
* The test runs against a kind cluster that is set up to look like a
  real kyma cluster
* The test can be run via `make test-integration`
* `run-kind.sh` script is split into `prepare-kind.sh` and
  `run-kind.sh`. `prepare-kind` just sets the cluster up with the cfapi
  operator itself + its dependencies. On top of it, `run-kind` applies
  the CF API resource so that we can play one that cluster
* The `run-tests.sh` script runs tests
* when running the integration test, `run-tests.sh` whould prepare the
  cluster (via `prepare-kind`), and run the integration test with
  ginkgo. The integration test applies the CFAPI resource and checks its
  state
* The cfapi controler currently does not clean up installed resources,
  therefore we temporarily clean them up in the test
  `SynchronizedAfterSuite`
* We use vendir to vendor `kpack`, `gateway-api` and `metrics-server`
  yamls under the `dependencies` directory
* The operator image Dockerfile picks kpack and gateway-api from
  `dependencies` instead of fetching them every time from their github latest release
* `make vendir-update-dependencies` updates all vendir dependencies

Co-authored-by: Yusmen Zabanov <yusmen.zabanov@sap.com>

diff --git a/development/assets/Dockerfile b/development/assets/Dockerfile
--- a/development/assets/Dockerfile
+++ b/development/assets/Dockerfile
@@ -7,7 +7,11 @@ FROM ${REGISTRY}/${IMG}:${VERSION} AS uploader
 ARG VERSION
 
 WORKDIR /workspace
-COPY release/$VERSION/korifi-${VERSION}.tgz korifi-${VERSION}.tgz
+# Copying the korifi tgz file via a wild card would not fail if the tgz does
+# not exist. We use this trick to support either using korifi from the uploader
+# (i.e. official Korifi release), or building a local dev Korifi version. This
+# Dockerfile would only replace Korifi if the tgz below exists
+COPY release/$VERSION/korifi-${VERSION}.tgz* /workspace
 COPY release/$VERSION/btp-service-broker btp-service-broker
 
 #--------
@@ -25,13 +29,14 @@ COPY --from=uploader /manager .
 
 COPY --chown=65532:65532 /module-data .
 COPY --from=uploader --chown=65532:65532  /module-data module-data/
-RUN rm -rf /module-data/korifi/*.tgz
-RUN rm -rf /module-data/btp-service-broker
 
 RUN yq -i eval '.spec.isCA = true'  module-data/certificates/certificates.tmpl
 
-COPY --from=uploader /workspace/korifi-${VERSION}.tgz /module-data/korifi/korifi-${VERSION}.tgz
+RUN rm -rf /module-data/btp-service-broker
 COPY --from=uploader /workspace/btp-service-broker /module-data/btp-service-broker
+
+COPY --from=uploader /workspace/korifi-${VERSION}.tgz* /
+RUN test -f /korifi-${VERSION}.tgz && rm -rf /module-data/korifi/*.tgz && cp /korifi-${VERSION}.tgz /module-data/korifi/korifi-${VERSION}.tgz || echo "Using pre-packaged Korifi"
 
 #--------
 FROM gcr.io/distroless/static:nonroot
